# automatically build the content about this site's _plugins
Jekyll::Hooks.register :site, :after_init do |site|
  acc = []
  Dir.each_child("_plugins"){ |filename|
    acc.push("## #{filename}\n#{(File.readlines(File.join("_plugins", filename)).map {|line| "    #{line}"}).join()}\n")
  }
  site.config['about-_plugins'] = "this page is generated by the plugin source below:\n#{acc.join()}"
  puts site.config['about-_plugins']
end

